pipeline:
    name: pipeline2
    identifier: pipeline2
    projectIdentifier: proj1
    orgIdentifier: default
    storeType: ""
    remoteType: create
    tags: {}
    stages:
        - stage:
              name: approval2
              identifier: approval2
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: approval2
                                identifier: approval2
                                type: JiraApproval
                                timeout: 1d
                                spec:
                                    approvalCriteria:
                                        type: KeyValues
                                        spec:
                                            matchAnyCondition: true
                                            conditions:
                                                - key: Status
                                                  operator: equals
                                                  value: DONE
                                    rejectionCriteria:
                                        type: KeyValues
                                        spec:
                                            matchAnyCondition: true
                                            conditions: []
                                    connectorRef: jira1
                                    projectKey: TJI
                                    issueKey: TJI-100708
              tags: {}
