pipeline:
    name: pipeline1
    identifier: pipeline1
    projectIdentifier: proj1
    orgIdentifier: default
    storeType: ""
    remoteType: create
    tags: {}
    stages:
        - stage:
              name: deploy
              identifier: deploy
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: service1
                      serviceDefinition:
                          spec:
                              variables: []
                          type: Kubernetes
                  infrastructure:
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: <+input>
                              namespace: <+input>
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                      environmentRef: environment
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
